### ISSUE TITLE
Deep-copy in reducer seems inefficient

### ISSUE THREAD

**Issue by markerikson** [tomat/react-reflorp#1]
Was skimming through the codebase trying to get a feel for how this library works.  Saw the use of `data[action.name].value[action.key]--;` and was at first concerned that the reducer was directly mutating state.  It looks like the line `extend(true, {}, state)` avoids that, but on the other hand the reducer is _always_ doing a deep copy of state, even if the action gets ignored by the reducer.  That seems like a waste of CPU cycles.  In addition, if everything is always deep copied, then components relying on data that wasn't modified by a given action could think that their data has actually changed because the references are different.

**Comment by tomat** [comment]
Thanks!

**Comment by markerikson** [comment]
Erm... looking at that diff, it appears that now that reducer really _is_ mutating state, which is definitely not good.

**Comment by tomat** [comment]
https://github.com/tomat/react-reflorp/blob/master/src/utils/reducer.js

**Comment by markerikson** [comment]
Cool.  Looks like it's now _not_ mutating, and only cloning when it has to.  I suspect you could probably switch it over to do shallow cloning instead if you updated the write logic appropriately, as the deep cloning might still cause components to update too often (see the Redux FAQ question on deep-cloning state for more info: http://redux.js.org/docs/FAQ.html#performance-clone-state).  Does look better, though.
