### ISSUE TITLE
Replace react-refetch connect function

### ISSUE THREAD

**Issue by dmitweb** [tomat/react-reflorp#2]
Can your add api to replace react-refetch connect function?
https://github.com/heroku/react-refetch ( // api-connector.js )

**Comment by tomat** [comment]
You mean this? https://github.com/tomat/react-reflorp#refetch-refetch

**Comment by dmitweb** [comment]
No.
`export default connect.defaults({
  buildRequest: function (mapping) {
    const options = {
      method: mapping.method,
      cache: 'force-cache',
      referrer: 'https://example.com',
      headers: mapping.headers,
      credentials: mapping.credentials,
      redirect: mapping.redirect,
      body: mapping.body
    }
    ...
})`

This is custom connect function from https://github.com/heroku/react-refetch. You can search this (api-connector.js).

**Comment by tomat** [comment]
This is now available in the new API for 1.0.
